name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # 当 main 分支有更新时触发

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 登录到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. 设置 Docker Buildx (用于更高级的构建特性)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 构建并推送到 Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: your-dockerhub-username/tg-signer:latest # 将 "your-dockerhub-username" 替换成你的用户名
